.TH libtrace 3
.SH NAME
libtrace \- a Debugging C Library

.SH LIBRARY
Debugging C library
.RI (libtrace,\ \-ltrace)

.SH SYNOPSIS
.nf
.B #include <trace/trace.h>
.PP
.B #define\ INFO_LEVEL\ \ \ \ 1\ //\ Normal\ messages
.B #define\ WARNING_LEVEL 2\ //\ Warning\ alert\ messages
.B #define\ ERROR_LEVEL\ \ \ 3\ //\ Error\ messages
.B #define\ FATAL_LEVEL\ \ \ 4\ //\ Fatal\ error\ messages
.B #define\ DEBUG_LEVEL\ \ \ 5\ //\ Messages\ with\ more\ information\ about\ the\ source\ code
.B #define\ TRACE_LEVEL\ \ \ 6\ //\ Show\ all\ messages\ in\ trace
.B 

.B #define\ INFO_DETAILS\ \ \ \ giDebugLevel\ >=\ INFO_LEVEL
.B #define\ WARNING_DETAILS\ giDebugLevel\ >=\ WARNING_LEVEL
.B #define\ ERROR_DETAILS\ \ \ giDebugLevel\ >=\ ERROR_LEVEL
.B #define\ FATAL_DETAILS\ \ \ giDebugLevel\ >=\ FATAL_LEVEL
.B #define\ DEBUG_DETAILS\ \ \ giDebugLevel\ >=\ DEBUG_LEVEL
.B #define\ TRACE_DETAILS\ \ \ giDebugLevel\ >=\ TRACE_LEVEL
.B

.B extern\ char\ gszTrace[256]
.B extern\ int\ giDebugLevel
 
.B void\ vSetTraceFileName(const\ char\ *kszLogFileName)
.B void\ vSetDebugLevel(const\ int\ kiDebugLevel)
.B int\ iGetLogLevel(void)
.B void\ _vTrace(const\ char\ *kpszModuleName,
.B\t\t\t\ \         const\ int\ kiLine,
.B\t\t\t\ \         const\ char\ *kpszFmt,\ ...)

.SH DESCRIPTION
This is a Debug C Library developed by Gustavo Bacagine. It is used in personal Bacagine C programs, but you can use this library in your programs too.

This is a free software

.SH USAGE\ EXAMPLES
You can see a usage examples of how to use this library at the github of the project at this link: <https://github.com/Bacagine/trace>

.SH BUGS
.PP
For reporting bugs, send a email to <gustavo.bacagine@protonmail.com>

.SH AUTHOR
.PP
Gustavo Bacagine <gustavo.bacagine@protonmail.com>
