.TH trace 1
.SH NAME
trace \- a Debugging C Library

.SH LIBRARY
Debugging C library
.RI (libtrace,\ \-ltrace)

.SH SYNOPSIS
.nf
.B #include <trace/trace.h>
.PP
.B #define\ INFO_LEVEL\t\t    0\ /*\ Normal\ messages\t\t\t\t\t\t\t\ \ \                          */
.B #define\ WARNING_LEVEL\t 1\ /*\ Warning\ alert\ messages\t\t\t\t\t\t\ \ \                      */
.B #define\ ERROR_LEVEL\t\t   2\ /*\ Error\ messages\t\t\t\t\t\t\t\ \ \                           */
.B #define\ FATAL_LEVEL\t\t   3\ /*\ Fatal\ error\ messages\t\t\t\t\t\t\ \ \                      */
.B #define\ DEBUG_LEVEL\t\t   4\ /*\ Messages\ with\ more\ information\ about\ the\ source\ code\ */
.B #define\ TRACE_LEVEL\t\t   5\ /*\ Show\ all\ messages\ in\ trace\t\t\t\t\t\ \ \                  */
.B 

.B #define\ INFO_LEVEL_LOG_LEVEL\t\    giDebugLevel\ >=\ INFO_LEVEL
.B #define\ WARNING_LEVEL_LOG_LEVEL\ giDebugLevel\ >=\ WARNING_LEVEL
.B #define\ ERROR_LEVEL_LOG_LEVEL\t\   giDebugLevel\ >=\ ERROR_LEVEL
.B #define\ FATAL_LEVEL_LOG_LEVEL\t\   giDebugLevel\ >=\ FATAL_LEVEL
.B #define\ DEBUG_LEVEL_LOG_LEVEL\t\   giDebugLevel\ >=\ DEBUG_LEVEL
.B #define\ TRACE_LEVEL_LOG_LEVEL\t\   giDebugLevel\ >=\ TRACE_LEVEL
.B

.B extern\ char\ gszConfFileName[256]
.B extern\ char\ gszLogFileName[256]
.B extern\ DebugLevel\ giDebugLevel
.B extern\ bool\ gbColoredLogLevel
 
.B void\ vSetConfFileName(const\ char\ *kszConfFile)
.B void\ vSetLogFileName(const\ char\ *kszLogFileName)
.B void\ vSetColoredLogLevel(bool\ bColored)
.B void\ vSetLogLevel(DebugLevel\ usiDebugLevel)
.B int\ iGetLogLevel(void)
.B int\ iGetColoredLogLevel(void)
.B void\ _vTrace(const\ DebugLevel\ usiDebugLevel,
.B\t\t\t\ \         const\ char\ *kpszModuleName,
.B\t\t\t\ \         const\ int\ kiLine,
.B\t\t\t\ \         const\ char\ *kpszFmt,\ ...)

.SH DESCRIPTION
This is a Debug C Library developed by Gustavo Bacagine. It is used in personal Bacagine C programs, but you can use this library in your programs too.

This is a free software licensed under the terms of the GPL3. You can should have received the copy of GLP3 license, if you don't have a copy, get the license at this link: <https://www.gnu.org/licenses/gpl-3.0.html>

.SH USAGE\ EXAMPLES
You can see a usage examples of how to use this library at the github of the project at this link: <https://github.com/Bacagine/trace>

.SH BUGS
.PP
For reporting bugs, send a email to <gustavo.bacagine@protonmail.com>

.SH AUTHOR
.PP
Gustavo Bacagine <gustavo.bacagine@protonmail.com>
